#!/usr/bin/with-contenv bash

echo "Starting Gunicorn"

[ -z "$PORT" ] && PORT="8080"
[ -z "$NUM_WORKERS" ] && NUM_WORKERS="4"

cd /app/jitsi || exit

exec \
  s6-setuidgid abc gunicorn \
    --bind 0.0.0.0:$PORT \
    --config /config/gunicorn/config.py \
    --workers $NUM_WORKERS \
    jitsi.wsgi
